// export function handleErrors(func: (...args: unknown[]) => Promise<unknown>) {
//   return async (...args: unknown[]) => {
//     try {
//       return await func(args);
//     } catch (error) {
//       console.error("Error - ", error);
//     }
//   };
// }
